### ISSUE TITLE
有没有小白跑服务端方法

### ISSUE THREAD

**Issue by SofaZhang** [WheatBox/WheatCloudSleep_correcting#10]
小白不会代码，安装了GCC，gcc -o main main.cpp，好像跑不起来，大佬可以带带小弟吗！

**Comment by ymx-mshk** [comment]
是windows环境还是linux环境？windows的话最好用vs。或者等我们提供一个release版本(也就是exe文件)，这样可以直接跑

**Comment by SofaZhang** [comment]
windows，但是我这边应该没什么环境，因为这边是小白，自己跑是不是还得搭一些C的环境？。等release比较方便吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月31日(星期三) 中午11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WheatBox/WheatCloudSleep] 有没有小白跑服务端方法 (Issue #10)





 
是windows环境还是linux环境？windows的话最好用vs。或者等我们提供一个release版本(也就是exe文件)，这样可以直接跑

**Comment by B1aNB1aN** [comment]
自己编译的话需要安装Visual Studio。等Release的话，什么都不需要安装，只需要下载，然后运行就好了。
跑服务器不需要安装任何依赖，我们这边会处理好。

**Comment by WheatBox** [comment]
这里~：https://docs.qq.com/doc/DTHlKbHROTWNMYUd1

**Comment by WheatBox** [comment]
这里~：https://docs.qq.com/doc/DTHlKbHROTWNMYUd1

**Comment by SofaZhang** [comment]
谢谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月31日(星期三) 中午11:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WheatBox/WheatCloudSleep] 有没有小白跑服务端方法 (Issue #10)





 
自己编译的话需要安装Visual Studio。等Release的话，什么都不需要安装，只需要下载，然后运行就好了。
 跑服务器不需要安装任何依赖，我们这边会处理好。
