### ISSUE TITLE
cmake生成项目文件一直报错

### ISSUE THREAD

**Issue by Taoshuaifei** [WheatBox/WheatCloudSleep_correcting#15]
cmake版本3.15
![截图](https://qiniu.handsomefly.cn/2022/09/14/05e5887195285.png)

**Comment by B1aNB1aN** [comment]
CMake什么版本？CMakeOutput.log里面说什么？

**Comment by Taoshuaifei** [comment]
> CMake什么版本？CMakeOutput.log里面说什么？

CMake版本3.15.0，CMakeOutput.log已附，我未能提取出关键信息
[CMakeOutput.log](https://github.com/WheatBox/WheatCloudSleep/files/9563787/CMakeOutput.log)

**Comment by B1aNB1aN** [comment]
把Line[70-73]都注释掉应该就好了。

**Comment by ymx-mshk** [comment]
最新提交已修复该问题
