### ISSUE TITLE
您好，发行版windows的版本屏幕亮度太暗了，请问是否有方法调节，谢谢！

### ISSUE THREAD

**Issue by Henoru** [WheatBox/WheatCloudSleep_correcting#20]

**Comment by WheatBox** [comment]
早上七点会开灯，晚上十点半会自动关灯

**Comment by super-zhang** [comment]
> 现在应该已经关灯了，你把Windows系统时间调到白天就好了

咦，服务器恢复了吗，怎么我还是连接失败呢

**Comment by Henoru** [comment]
哦哦感谢你，我在本地运行了服务器的代码，连上去体验了一下（




------------------&nbsp;Original message&nbsp;------------------
From: "heno"; 
Sendtime: Friday, Sep 16, 2022 10:19 AM
To: "WheatBox/WheatCloudSleep_correcting"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [WheatBox/WheatCloudSleep_correcting] 您好，发行版windows的版本屏幕亮度太暗了，请问是否有方法调节，谢谢！ (Issue #20)





  
现在应该已经关灯了，你把Windows系统时间调到白天就好了
  
咦，服务器恢复了吗，怎么我还是连接失败呢
