### ISSUE TITLE
linux服务器怎么部署这个项目?

### ISSUE THREAD

**Issue by Nike-Chen-C** [WheatBox/WheatCloudSleep_correcting#25]
小白一个,麻烦问一下.此项目服务器端(centos7.9),如何部署这个?最好能有详细步骤,感谢

**Comment by zhhhhhhhh** [comment]
clone到本地后直接cmake.
然后make 就可以看到可运行文件了
晚点我看看写个教程吧，并不困难

**Comment by labman010** [comment]
参考CMakeLists.txt文件中的注释

**Comment by zhhhhhhhh** [comment]
详细教程已经更新到cmake-asio-server分支下
