### ISSUE TITLE
编译到room.cpp报错

### ISSUE THREAD

**Issue by giteRdroid** [WheatBox/WheatCloudSleep_correcting#26]
提示：Source/Server/CloudSleepServer/room.cpp:161:30: error: unused parameter 'src_id' [-Werror=unused-parameter]
编译不下去了，我这边需要改点啥。。Linux系统的。
系统环境：CentOS 7.9
编译环境：gcc version 12.2.0

**Comment by WheatBox** [comment]
嗯，昨晚上实装json的时候忘了删掉旧的变量了，这就去修一下，修好后会回来给你留言

**Comment by WheatBox** [comment]
哦对了，目前最新的分支里的客户端需要搭配场景包才能使用，服务端与旧客户端不兼容，能制作场景包的编辑器做好了，但是感觉还有几处需要修改，就暂时还没放出来

**Comment by WheatBox** [comment]
旧版客户端（画面上只有256张床的那个）能使用的服务端的源代码在Release里，“经典版本Classic”

**Comment by WheatBox** [comment]
修好了

**Comment by giteRdroid** [comment]
666啊，这速率可以。新客户端的场景包目前有现成的吗？

**Comment by WheatBox** [comment]
这是可以自由创作场景包的编辑器的Github链接：
https://github.com/WheatBox/CloudSleepEngine

**Comment by WheatBox** [comment]
几分钟前我刚public出来的↑

**Comment by giteRdroid** [comment]
来来来，新问题哈哈哈。
wheat_command.cpp:30:31: error: NULL used in arithmetic [-Werror=pointer-arith]

**Comment by giteRdroid** [comment]
我还是先试试已经发布出来的版本编译看看，star一下等你做完场景编辑器。哈哈哈

**Comment by cn720map** [comment]
无基础菜鸡求助：
[root@server build]# make install
make: *** No rule to make target `install'.  Stop.

环境：
centos 7.9 
gcc version 11.2.1 20220127 (Red Hat 11.2.1-9) (GCC)
cmake version 3.6.2

**Comment by zhhhhhhhh** [comment]
> 无基础菜鸡求助：
> [root@server build]# make
> make: *** No targets specified and no makefile found. Stop.
> 
> 环境：
> centos 7.9 
> gcc version 11.2.1 20220127 (Red Hat 11.2.1-9) (GCC)
> cmake version 3.6.2

请参考:https://docs.qq.com/doc/DTHlKbHROTWNMYUd1

**Comment by cn720map** [comment]
> > 无基础菜鸡求助： [root@server build]# make make： *** 未指定目标，也未找到生成文件。停。
> > 环境： centos 7.9 gcc 版本 11.2.1 20220127 （Red Hat 11.2.1-9） （GCC） 版本 3.6.2
> 
> 请参考：https://docs.qq.com/doc/DTHlKbHROTWNMYUd1

已解决，CMake版本过低，但是又报了个新的错误：
CMake Error at CMakeLists.txt:70 (target_link_options):
  target_link_options called with incorrect number of arguments

**Comment by giteRdroid** [comment]
> 

最新的代码多少有点问题，我之前编译的时候也出现问题了，我自己编译都是走docker编译的，建议你下载已经Release的code进行编译操作。

**Comment by giteRdroid** [comment]
> > > 无基础菜鸡求助： [root@server build]# make make： *** 未指定目标，也未找到生成文件。停。
> > > 环境： centos 7.9 gcc 版本 11.2.1 20220127 （Red Hat 11.2.1-9） （GCC） 版本 3.6.2
> > 
> > 
> > 请参考：https://docs.qq.com/doc/DTHlKbHROTWNMYUd1
> 
> 已解决，CMake版本过低，但是又报了个新的错误： CMake Error at CMakeLists.txt:70 (target_link_options): target_link_options called with incorrect number of arguments

最新的代码多少有点问题，我之前编译的时候也出现问题了，我自己编译都是走docker编译的，建议你下载已经Release的code进行编译操作。

**Comment by cn720map** [comment]
> > > > 无基础菜鸡求助： [root@server build]# make make： *** 未指定目标，也未找到生成文件。停。
> > > > 环境： centos 7.9 gcc 版本 11.2.1 20220127 （Red Hat 11.2.1-9） （GCC） 版本 3.6.2
> > > 
> > > 
> > > 请参考：https://docs.qq.com/doc/DTHlKbHROTWNMYUd1
> > 
> > 
> > 已解决，CMake版本过低，但是又报了个新的错误： CMake Error at CMakeLists.txt:70 (target_link_options): target_link_options called with incorrect number of arguments
> 
> 最新的代码多少有点问题，我之前编译的时候也出现问题了，建议你下载已经Release的code进行编译操作。我自己编译都是走docker编译的，后面还有一大堆动态库问题，我最后都是走docker编译，直接在容器里面运行。

好的，谢谢您的解答！我尝试重新下载已经Release的code进行编译。

**Comment by B1aNB1aN** [comment]
> 

你把CMakeLists.txt文件里面70行和下面的圆括号注释掉就行了。这个在最新的代码里面已经修复了。

**Comment by B1aNB1aN** [comment]
> > > 无基础菜鸡求助： [root@server build]# make make： *** 未指定目标，也未找到生成文件。停。
> > > 环境： centos 7.9 gcc 版本 11.2.1 20220127 （Red Hat 11.2.1-9） （GCC） 版本 3.6.2
> > 
> > 
> > 请参考：https://docs.qq.com/doc/DTHlKbHROTWNMYUd1
> 
> 已解决，CMake版本过低，但是又报了个新的错误： CMake Error at CMakeLists.txt:70 (target_link_options): target_link_options called with incorrect number of arguments

你把70行那个target_link_options和下面的圆括号注释掉就好了。

**Comment by giteRdroid** [comment]
> > > > > 无基础菜鸡求助： [root@server build]# make make： *** 未指定目标，也未找到生成文件。停。
> > > > > 环境： centos 7.9 gcc 版本 11.2.1 20220127 （Red Hat 11.2.1-9） （GCC） 版本 3.6.2
> > > > 
> > > > 
> > > > 请参考：https://docs.qq.com/doc/DTHlKbHROTWNMYUd1
> > > 
> > > 
> > > 已解决，CMake版本过低，但是又报了个新的错误： CMake Error at CMakeLists.txt:70 (target_link_options): target_link_options called with incorrect number of arguments
> > 
> > 
> > 最新的代码多少有点问题，我之前编译的时候也出现问题了，建议你下载已经Release的code进行编译操作。我自己编译都是走docker编译的，后面还有一大堆动态库问题，我最后都是走docker编译，直接在容器里面运行。
> 
> 好的，谢谢您的解答！我尝试重新下载已经Release的code进行编译。

哦对了，最新的Release好像没有Linux的，你估计得找作者修复Linux编译的那个分支。不好意思我说漏了

**Comment by cn720map** [comment]
> > > > 无基础菜鸡求助： [root@server build]# make make： *** 未指定目标，也未找到生成文件。停。
> > > > 环境： centos 7.9 gcc 版本 11.2.1 20220127 （Red Hat 11.2.1-9） （GCC） 版本 3.6.2
> > > 
> > > 
> > > 请参考：https://docs.qq.com/doc/DTHlKbHROTWNMYUd1
> > 
> > 
> > 已解决，CMake版本过低，但是又报了个新的错误： CMake Error at CMakeLists.txt:70 (target_link_options): target_link_options called with incorrect number of arguments
> 
> 你把70行那个target_link_options和下面的圆括号注释掉就好了。

好的谢谢！我看了一下，已经是注释掉的了，去掉注释后按照教程能进入下一步，但新的问题是：
[ 15%] Building CXX object CMakeFiles/CloudSleepServer.dir/config.cpp.o
/home/WheatCloudSleep/Source/Server/CloudSleepServer/config.cpp: In constructor ‘wheat::ViolationRules::ViolationRules()’:
/home/WheatCloudSleep/Source/Server/CloudSleepServer/config.cpp:149:42: error: missing initializer for member ‘wheat::ViolationRules::ViolationRuleKey::id’ [-Werror=missing-field-initializers]
  149 |     rules.emplace(ViolationRuleKey{ "ip" }, "conn=5,pps=100,bps=81920");
      |                                          ^
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/CloudSleepServer.dir/config.cpp.o] Error 1
make[1]: *** [CMakeFiles/CloudSleepS
![Snipaste_2022-09-27_12-52-06](https://user-images.githubusercontent.com/35869860/192435009-9c7e54c4-a7a5-4e3e-970b-3f63d10bd75a.jpg)
erver.dir/all] Error 2
make: *** [all] Error 2
[root@server build]#

**Comment by cn720map** [comment]
> > > > 无基础菜鸡求助： [root@server build]# make make： *** 未指定目标，也未找到生成文件。停。
> > > > 环境： centos 7.9 gcc 版本 11.2.1 20220127 （Red Hat 11.2.1-9） （GCC） 版本 3.6.2
> > > 
> > > 
> > > 请参考：https://docs.qq.com/doc/DTHlKbHROTWNMYUd1
> > 
> > 
> > 已解决，CMake版本过低，但是又报了个新的错误： CMake Error at CMakeLists.txt:70 (target_link_options): target_link_options called with incorrect number of arguments
> 
> 你把70行那个target_link_options和下面的圆括号注释掉就好了。

好的谢谢！我看了一下，已经是注释掉的了，去掉注释后按照教程能进入下一步，但新的问题是：
[ 15%] Building CXX object CMakeFiles/CloudSleepServer.dir/config.cpp.o
/home/WheatCloudSleep/Source/Server/CloudSleepServer/config.cpp: In constructor ‘wheat::ViolationRules::ViolationRules()’:
/home/WheatCloudSleep/Source/Server/CloudSleepServer/config.cpp:149:42: error: missing initializer for member ‘wheat::ViolationRules::ViolationRuleKey::id’ [-Werror=missing-field-initializers]
  149 |     rules.emplace(ViolationRuleKey{ "ip" }, "conn=5,pps=100,bps=81920");
      |                                          ^
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/CloudSleepServer.dir/config.cpp.o] Error 1
make[1]: *** [CMakeFiles/CloudSleepServer.dir/all] Error 2
make: *** [all] Error 2
[root@server build]# 

![Snipaste_2022-09-27_12-52-06](https://user-images.githubusercontent.com/35869860/192435250-36d2586e-7fd6-4c0b-ab53-7671ddcfbc4b.jpg)

**Comment by cn720map** [comment]
> > > > > > 无基础菜鸡求助： [root@server build]# make make： *** 未指定目标，也未找到生成文件。停。
> > > > > > 环境： centos 7.9 gcc 版本 11.2.1 20220127 （Red Hat 11.2.1-9） （GCC） 版本 3.6.2
> > > > > 
> > > > > 
> > > > > 请参考：https://docs.qq.com/doc/DTHlKbHROTWNMYUd1
> > > > 
> > > > 
> > > > 已解决，CMake版本过低，但是又报了个新的错误： CMake Error at CMakeLists.txt:70 (target_link_options): target_link_options called with incorrect number of arguments
> > > 
> > > 
> > > 最新的代码多少有点问题，我之前编译的时候也出现问题了，建议你下载已经Release的code进行编译操作。我自己编译都是走docker编译的，后面还有一大堆动态库问题，我最后都是走docker编译，直接在容器里面运行。
> > 
> > 
> > 好的，谢谢您的解答！我尝试重新下载已经Release的code进行编译。
> 
> 哦对了，最新的Release好像没有Linux的，你估计得找作者修复Linux编译的那个分支。不好意思我说漏了

好像是有的吧：Source code (tar.gz)

**Comment by giteRdroid** [comment]
> > > > > > > 无基础菜鸡求助： [root@server build]# make make： *** 未指定目标，也未找到生成文件。停。
> > > > > > > 环境： centos 7.9 gcc 版本 11.2.1 20220127 （Red Hat 11.2.1-9） （GCC） 版本 3.6.2
> > > > > > 
> > > > > > 
> > > > > > 请参考：https://docs.qq.com/doc/DTHlKbHROTWNMYUd1
> > > > > 
> > > > > 
> > > > > 已解决，CMake版本过低，但是又报了个新的错误： CMake Error at CMakeLists.txt:70 (target_link_options): target_link_options called with incorrect number of arguments
> > > > 
> > > > 
> > > > 最新的代码多少有点问题，我之前编译的时候也出现问题了，建议你下载已经Release的code进行编译操作。我自己编译都是走docker编译的，后面还有一大堆动态库问题，我最后都是走docker编译，直接在容器里面运行。
> > > 
> > > 
> > > 好的，谢谢您的解答！我尝试重新下载已经Release的code进行编译。
> > 
> > 
> > 哦对了，最新的Release好像没有Linux的，你估计得找作者修复Linux编译的那个分支。不好意思我说漏了
> 
> 好像是有的吧：Source code (tar.gz)

没有。现在的Release是没有修复Linux编译的，有一个分支是修复了Linux编译的

**Comment by cn720map** [comment]
> > > > > > > > 无基础菜鸡求助： [root@server build]# make make： *** 未指定目标，也未找到生成文件。停。
> > > > > > > > 环境： centos 7.9 gcc 版本 11.2.1 20220127 （Red Hat 11.2.1-9） （GCC） 版本 3.6.2
> > > > > > > 
> > > > > > > 
> > > > > > > 请参考：https://docs.qq.com/doc/DTHlKbHROTWNMYUd1
> > > > > > 
> > > > > > 
> > > > > > 已解决，CMake版本过低，但是又报了个新的错误： CMake Error at CMakeLists.txt:70 (target_link_options): target_link_options called with incorrect number of arguments
> > > > > 
> > > > > 
> > > > > 最新的代码多少有点问题，我之前编译的时候也出现问题了，建议你下载已经Release的code进行编译操作。我自己编译都是走docker编译的，后面还有一大堆动态库问题，我最后都是走docker编译，直接在容器里面运行。
> > > > 
> > > > 
> > > > 好的，谢谢您的解答！我尝试重新下载已经Release的code进行编译。
> > > 
> > > 
> > > 哦对了，最新的Release好像没有Linux的，你估计得找作者修复Linux编译的那个分支。不好意思我说漏了
> > 
> > 
> > 好像是有的吧：Source code (tar.gz)
> 
> 没有。现在的Release是没有修复Linux编译的，有一个分支是修复了Linux编译的

好的好的，非常感谢，那就等等作者修复喽~

**Comment by giteRdroid** [comment]
> > > > > > > > > 无基础菜鸡求助： [root@server build]# make make： *** 未指定目标，也未找到生成文件。停。
> > > > > > > > > 环境： centos 7.9 gcc 版本 11.2.1 20220127 （Red Hat 11.2.1-9） （GCC） 版本 3.6.2
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 请参考：https://docs.qq.com/doc/DTHlKbHROTWNMYUd1
> > > > > > > 
> > > > > > > 
> > > > > > > 已解决，CMake版本过低，但是又报了个新的错误： CMake Error at CMakeLists.txt:70 (target_link_options): target_link_options called with incorrect number of arguments
> > > > > > 
> > > > > > 
> > > > > > 最新的代码多少有点问题，我之前编译的时候也出现问题了，建议你下载已经Release的code进行编译操作。我自己编译都是走docker编译的，后面还有一大堆动态库问题，我最后都是走docker编译，直接在容器里面运行。
> > > > > 
> > > > > 
> > > > > 好的，谢谢您的解答！我尝试重新下载已经Release的code进行编译。
> > > > 
> > > > 
> > > > 哦对了，最新的Release好像没有Linux的，你估计得找作者修复Linux编译的那个分支。不好意思我说漏了
> > > 
> > > 
> > > 好像是有的吧：Source code (tar.gz)
> > 
> > 
> > 没有。现在的Release是没有修复Linux编译的，有一个分支是修复了Linux编译的
> 
> 好的好的，非常感谢，那就等等作者修复喽~

不好意思说错了，刚睡醒，是一个历史版本：https://github.com/WheatBox/WheatCloudSleep_correcting/tree/739b555a9e69dd94e3e9a1f219006687e1855a0f
你从这个历史版本的代码编译应该就行了，不过可能会遇到动态库版本过低，建议该升级的升级一下

**Comment by cn720map** [comment]
> 

十分感谢大佬的耐心指导！谢谢~ 已成功编译~

![Uploading Snipaste_2022-09-27_14-09-43.jpg…]()

**Comment by cn720map** [comment]
> > > > > > > > > > 无基础菜鸡求助： [root@server build]# make make： *** 未指定目标，也未找到生成文件。停。
> > > > > > > > > > 环境： centos 7.9 gcc 版本 11.2.1 20220127 （Red Hat 11.2.1-9） （GCC） 版本 3.6.2
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 请参考：https://docs.qq.com/doc/DTHlKbHROTWNMYUd1
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 已解决，CMake版本过低，但是又报了个新的错误： CMake Error at CMakeLists.txt:70 (target_link_options): target_link_options called with incorrect number of arguments
> > > > > > > 
> > > > > > > 
> > > > > > > 最新的代码多少有点问题，我之前编译的时候也出现问题了，建议你下载已经Release的code进行编译操作。我自己编译都是走docker编译的，后面还有一大堆动态库问题，我最后都是走docker编译，直接在容器里面运行。
> > > > > > 
> > > > > > 
> > > > > > 好的，谢谢您的解答！我尝试重新下载已经Release的code进行编译。
> > > > > 
> > > > > 
> > > > > 哦对了，最新的Release好像没有Linux的，你估计得找作者修复Linux编译的那个分支。不好意思我说漏了
> > > > 
> > > > 
> > > > 好像是有的吧：Source code (tar.gz)
> > > 
> > > 
> > > 没有。现在的Release是没有修复Linux编译的，有一个分支是修复了Linux编译的
> > 
> > 
> > 好的好的，非常感谢，那就等等作者修复喽~
> 
> 不好意思说错了，刚睡醒，是一个历史版本：https://github.com/WheatBox/WheatCloudSleep_correcting/tree/739b555a9e69dd94e3e9a1f219006687e1855a0f 你从这个历史版本的代码编译应该就行了，不过可能会遇到动态库版本过低，建议该升级的升级一下

十分感谢大佬的耐心指导！谢谢~ 已成功编译~

![Snipaste_2022-09-27_14-09-43](https://user-images.githubusercontent.com/35869860/192446894-45960a2c-4e97-4bb8-bc7e-d3ee301b490b.jpg)
