### ISSUE TITLE
可否建一个吹水群（

### ISSUE THREAD

**Issue by Sbaoor-fly** [WheatBox/WheatCloudSleep_correcting#27]
最近几天登不上去来看看怎么回事，~*原来是喝茶了*~
也方便我们提建议反馈bug什么的
tg或者discord都行，能找到这来的人~应该~都知道怎么翻出去）

**Comment by WheatBox** [comment]
有个玩家朋友们建的QQ群，951278082，加好后麻烦在这里回复一下，我会删一下我这条留言，防止有些奇奇怪怪的人看到后加进来（例如麦片哥）

**Comment by Sbaoor-fly** [comment]
谢谢，加好了
