### ISSUE TITLE
连不上诶

### ISSUE THREAD

**Issue by I-Good-Vegetable** [WheatBox/WheatCloudSleep_correcting#3]
支持海外用户么~我在国外连不上哇

**Comment by WheatBox** [comment]
嗯，很迷，我现在自己也连不上去了，人一多我就连不上了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WheatBox/WheatCloudSleep"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月27日(星期六) 上午10:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[WheatBox/WheatCloudSleep] 连不上诶 (Issue #3)





 
支持海外用户么~我在国外连不上哇

**Comment by I-Good-Vegetable** [comment]
啊~酱紫啊~要不搞个vip~收点钱买个好点的服务器~

**Comment by I-Good-Vegetable** [comment]
要不然睡不了觉了额呜呜呜

**Comment by WheatBox** [comment]
抱歉一直忘了回复，这么久过去了，刚才才想起来
在服务器新的防护系统上线后一直很稳定，再也没有崩溃过，也没有被攻击打垮过，现在可以放心了
客户端现在的版本也更新到了 0.3.2，也有了几个新功能，可以在简介里下载到新版本
