### ISSUE TITLE
[Enhancement] 请考虑使用第三方库,以及性能改进

### ISSUE THREAD

**Issue by caizhe666** [WheatBox/WheatCloudSleep_correcting#6]
# 问题描述

1. 使用了原始的Winsock2,代码比较混乱.
2. 不够安全,且信息中记录了用户IP,属于隐私内容,建议进行加密
3. WheatBedManager::FindSleeperId方法中使用遍历加std::vector

# 解决方法

1. 请不要重复造轮子,使用例如[asio](https://think-async.com/Asio),来进行TCP管理
2. 使用cryptopp进行加密
3. 使用std::map

**Comment by WheatBox** [comment]
了解了，谢谢

**Comment by Doona-Jazen** [comment]
4.核心业务可以增加线程池优化处理
5.服务器部署可增加负载均衡

**Comment by WheatBox** [comment]
明白，这些我们后面会试着去解决，不过现在我们遇到了一个大问题，就是昨晚上和前天晚上开服的时候都有人在涉政，还有辱骂领导人，用领导人姓名做角色名称，我们现在正在解决这个大难题，正在开发一套投票踢人系统

**Comment by WheatBox** [comment]
感谢二位

**Comment by caizhe666** [comment]
> 明白，这些我们后面会试着去解决，不过现在我们遇到了一个大问题，就是昨晚上和前天晚上开服的时候都有人在涉政，还有辱骂领导人，用领导人姓名做角色名称，我们现在正在解决这个大难题，正在开发一套投票踢人系统

只需要进行过滤和发言冷却即可

**Comment by caizhe666** [comment]
> 感谢二位

另外我也想进群,没找到QQ号

**Comment by WheatBox** [comment]
嗯，可以的，目前有一个我自己建的小群专门用作自己的内部交流，和一个其他观众朋友们建的大群，你想进哪一个，我拉你

**Comment by caizhe666** [comment]
我进小群吧,我现在在封装一个网络库给GameMaker用,希望能解决你的bug

**Comment by WheatBox** [comment]
嗯，好的，B站私聊发我你的QQ吧~

**Comment by paradox8599** [comment]
@WheatBox 您好，请问可以把我拉进群聊吗，最近也在构思一个类似的社交游戏，想找同好交流学习一下

**Comment by paradox8599** [comment]
@WheatBox  
您好，我最近也在构思一个类似的社交游戏。能否让我也加入群聊，交流学习一下？
